spring:
  flyway:
    baseline-on-migrate: false
#  jpa:
#    hibernate:
#      ddl-auto: none
  application:
    name: game-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost}:8888

settings:
  access_token:
  clientId: