spring:
  application:
    name: game-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis