spring:
#  flyway:
#    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: game-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost}:8888

settings:
  access_token: mn1pm8dmvdrj4l5hhwgphqm8t5pd1w
  clientId: ejhvpt8h93s7917kbhjtq6r0y66wqj