apiVersion: v1
kind: Service
metadata:
  name: social-service
  namespace: gamelist
spec:
  selector:
    app: social-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: LoadBalancer