@hostname = http://localhost:8081

###
post {{hostname}}/api/v1/likes
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZAZ21haWwuY29tIiwiZXhwIjoxNzE5NjkyNzEwLCJpYXQiOjE3MTk2ODkxMTAsImlzcyI6ImdhbWVsaXN0LWF1dGgtc2VydmljZSIsInN1YiI6IjY2N2Y4YTE4YTgzYTQwMGE4Y2MxNWE4MCJ9.ux7iZZ4awjXEGuEMeqyNLVOMDgyJGgJON1vInLAlnhU

{
    "interactiveEntityId": 2
}

###
delete {{hostname}}/api/v1/likes/1
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZAZ21haWwuY29tIiwiZXhwIjoxNzE5NjkyNzEwLCJpYXQiOjE3MTk2ODkxMTAsImlzcyI6ImdhbWVsaXN0LWF1dGgtc2VydmljZSIsInN1YiI6IjY2N2Y4YTE4YTgzYTQwMGE4Y2MxNWE4MCJ9.ux7iZZ4awjXEGuEMeqyNLVOMDgyJGgJON1vInLAlnhU

###
post {{hostname}}/api/v1/comments
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZAZ21haWwuY29tIiwiZXhwIjoxNzE5NjkyNzEwLCJpYXQiOjE3MTk2ODkxMTAsImlzcyI6ImdhbWVsaXN0LWF1dGgtc2VydmljZSIsInN1YiI6IjY2N2Y4YTE4YTgzYTQwMGE4Y2MxNWE4MCJ9.ux7iZZ4awjXEGuEMeqyNLVOMDgyJGgJON1vInLAlnhU

{
    "interactiveEntityId": 3,
    "text": "Hello world 33333"
}

###
delete {{hostname}}/api/v1/comments/1253
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZAZ21haWwuY29tIiwiZXhwIjoxNzE5NjkyNzEwLCJpYXQiOjE3MTk2ODkxMTAsImlzcyI6ImdhbWVsaXN0LWF1dGgtc2VydmljZSIsInN1YiI6IjY2N2Y4YTE4YTgzYTQwMGE4Y2MxNWE4MCJ9.ux7iZZ4awjXEGuEMeqyNLVOMDgyJGgJON1vInLAlnhU

###
put {{hostname}}/api/v1/comments/1252
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZAZ21haWwuY29tIiwiZXhwIjoxNzE5NjkyNzEwLCJpYXQiOjE3MTk2ODkxMTAsImlzcyI6ImdhbWVsaXN0LWF1dGgtc2VydmljZSIsInN1YiI6IjY2N2Y4YTE4YTgzYTQwMGE4Y2MxNWE4MCJ9.ux7iZZ4awjXEGuEMeqyNLVOMDgyJGgJON1vInLAlnhU

{
    "interactiveEntityId": 2,
    "text": "Hello world 2222222"
}

###
get {{hostname}}/api/v1/posts
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZAZ21haWwuY29tIiwiZXhwIjoxNzE5NjkyNzEwLCJpYXQiOjE3MTk2ODkxMTAsImlzcyI6ImdhbWVsaXN0LWF1dGgtc2VydmljZSIsInN1YiI6IjY2N2Y4YTE4YTgzYTQwMGE4Y2MxNWE4MCJ9.ux7iZZ4awjXEGuEMeqyNLVOMDgyJGgJON1vInLAlnhU

###
get {{hostname}}/api/v1/posts/all
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZAZ21haWwuY29tIiwiZXhwIjoxNzE5NjkyNzEwLCJpYXQiOjE3MTk2ODkxMTAsImlzcyI6ImdhbWVsaXN0LWF1dGgtc2VydmljZSIsInN1YiI6IjY2N2Y4YTE4YTgzYTQwMGE4Y2MxNWE4MCJ9.ux7iZZ4awjXEGuEMeqyNLVOMDgyJGgJON1vInLAlnhU

###
get {{hostname}}/api/v1/posts/527
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZAZ21haWwuY29tIiwiZXhwIjoxNzE5NjkyNzEwLCJpYXQiOjE3MTk2ODkxMTAsImlzcyI6ImdhbWVsaXN0LWF1dGgtc2VydmljZSIsInN1YiI6IjY2N2Y4YTE4YTgzYTQwMGE4Y2MxNWE4MCJ9.ux7iZZ4awjXEGuEMeqyNLVOMDgyJGgJON1vInLAlnhU

###
post {{hostname}}/api/v1/posts
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80

{
  "userId": "667f8a18a83a400a8cc15a80",
  "text": "This is a postttttt!"
}

###
put {{hostname}}/api/v1/posts/527
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80

{
  "userId": "667f8a18a83a400a8cc15a80",
  "text": "This is a postttttt editttttt!"
}


###
delete {{hostname}}/api/v1/posts/528
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80

###
get {{hostname}}/api/v1/interactive-entities/forum-pageable
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZAZ21haWwuY29tIiwiZXhwIjoxNzE5NjkyNzEwLCJpYXQiOjE3MTk2ODkxMTAsImlzcyI6ImdhbWVsaXN0LWF1dGgtc2VydmljZSIsInN1YiI6IjY2N2Y4YTE4YTgzYTQwMGE4Y2MxNWE4MCJ9.ux7iZZ4awjXEGuEMeqyNLVOMDgyJGgJON1vInLAlnhU

###
get {{hostname}}/api/v1/interactive-entities/user-social/pageable
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZAZ21haWwuY29tIiwiZXhwIjoxNzE5NjkyNzEwLCJpYXQiOjE3MTk2ODkxMTAsImlzcyI6ImdhbWVsaXN0LWF1dGgtc2VydmljZSIsInN1YiI6IjY2N2Y4YTE4YTgzYTQwMGE4Y2MxNWE4MCJ9.ux7iZZ4awjXEGuEMeqyNLVOMDgyJGgJON1vInLAlnhU

###
get {{hostname}}/api/v1/interactive-entities/user-social
Content-Type: application/json
userId: 667f8a18a83a400a8cc15a80
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZAZ21haWwuY29tIiwiZXhwIjoxNzE5NjkyNzEwLCJpYXQiOjE3MTk2ODkxMTAsImlzcyI6ImdhbWVsaXN0LWF1dGgtc2VydmljZSIsInN1YiI6IjY2N2Y4YTE4YTgzYTQwMGE4Y2MxNWE4MCJ9.ux7iZZ4awjXEGuEMeqyNLVOMDgyJGgJON1vInLAlnhU
