   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: auth-service
     namespace: gamelist
   spec:
     replicas: 2
     selector:
       matchLabels:
         app: auth-service
     strategy:
       rollingUpdate:
         maxSurge: 25%
         maxUnavailable: 25%
       type: RollingUpdate
     template:
       metadata:
         labels:
           app: auth-service
       spec:
         schedulerName: default-scheduler
         restartPolicy: Always
         dnsPolicy: ClusterFirst
         securityContext: {}
         terminationGracePeriodSeconds: 30
         containers:
         - name: auth-service
           image: tienviet/gamelist-auth-service:latest
           imagePullPolicy: Always
           ports:
           - containerPort: 8082
           env:
            - name: PORT
              value: "8082"
           resources: {}
          #  resources:
          #    requests:
          #      memory: "512Mi"
          #      cpu: "500m"
          #    limits:
          #      memory: "1Gi"
          #      cpu: "1000m"