apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: gamelist
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
    name: http
  - protocol: TCP
    port: 6567
    targetPort: 6567
    name: grpc
  type: ClusterIP