apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: gamelist
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
  type: ClusterIP