spring:
  application:
    name: api-gateway
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 20
        multiplier: 1.1
        max-interval: 10000
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost}:8888

security:
  jwt:
    secret-key: jkhoiuvsnoiergtbyabdyuweaobcaljcsbejoiufydsbu