spring:
  application:
    name: api-gateway
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 20
        multiplier: 1.1
        max-interval: 10000
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

security:
  jwt:
    secret-key: ${JWT_SECRET:jkhoiuvsnoiergtbyabdyuweaobcaljcsbejoiufydsbu}