name: 'spring-boot-microservices-gamelist'
services:
  config-server:
    image: tienviet/gamelist-config-server
    container_name: config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/game
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8888:8888"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  api-gateway:
    image: tienviet/gamelist-api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GAMELIST_SERVICE_URL=http://game-service:8080
      #      - ORDER_SERVICE_URL=http://order-service:8082
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
      - CONFIG_SERVER_URL=config-server
    ports:
      - "8989:8989"
    restart: unless-stopped
    depends_on:
      - config-server
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  game-service:
    image: tienviet/gamelist-game-service
    container_name: game-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://gamelist-dev-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/game
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
      - CONFIG_SERVER_URL=config-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"