name: 'spring-boot-microservices-gamelist'
services:
  api-gateway:
    image: tienviet/gamelist-api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GAME_SERVICE_URL=http://game-service:8083
      - AUTH_SERVICE_URL=http://auth-service:8082
      - SOCIAL_SERVICE_URL=http://social-service:8081
      - USER_SERVICE_URL=http://user-service:8080
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
      - CONFIG_SERVER_URL=http://config-server:8888
    ports:
      - "8989:8989"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  #  auth-service:
  #    image: tienviet/gamelist-auth-service
  #    container_name: auth-service
  #    environment:
  #      - SPRING_PROFILES_ACTIVE=docker
  #      - DB_URL=jdbc:postgresql://gamelist-dev-db:5432/postgres
  #      - DB_USERNAME=postgres
  #      - DB_PASSWORD=postgres
  #      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/auth-service
  #      - MANAGEMENT_TRACING_ENABLED=true
  #      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
  #      - CONFIG_SERVER_URL=http://config-server:8888
  #    ports:
  #      - "8082:8082"
  #    restart: unless-stopped
  #    deploy:
  #      resources:
  #        limits:
  #          memory: 700m
  #    labels:
  #      logging: "promtail"

  game-service:
    image: tienviet/gamelist-game-service
    container_name: game-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://gamelist-dev-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/game-service
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
      - CONFIG_SERVER_URL=http://config-server:8888
      - USER_SERVICE_URL=http://api-gateway:8989/user-service
      - AUTH_SERVICE_ADDRESS=auth-service:6567
      - USER_SERVICE_ADDRESS=user-service:6568
    ports:
      - "8083:8083"
      - "6565:6565"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
    labels:
      logging: "promtail"

  social-service:
    image: tienviet/gamelist-social-service
    container_name: social-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://gamelist-dev-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/social-service
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
      - CONFIG_SERVER_URL=http://config-server:8888
      - GAME_SERVICE_URL=http://api-gateway:8989/game-service
      #      - GO_SERVICE_URL=http://api-gateway:8989/go-service
      - USER_SERVICE_URL=http://api-gateway:8989/user-service
      - AUTH_SERVICE_ADDRESS=auth-service:6567
      - USER_SERVICE_ADDRESS=user-service:6568
    ports:
      - "8081:8081"
      - "6566:6566"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
    labels:
      logging: "promtail"

  #  user-service:
  #    image: tienviet/gamelist-user-service
  #    container_name: user-service
  #    environment:
  #      - SPRING_PROFILES_ACTIVE=docker
  #      - DB_URL=jdbc:postgresql://gamelist-dev-db:5432/postgres
  #      - DB_USERNAME=postgres
  #      - DB_PASSWORD=postgres
  #      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/user-service
  #      - MANAGEMENT_TRACING_ENABLED=true
  #      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
  #      - CONFIG_SERVER_URL=http://config-server:8888
  #    ports:
  #      - "8083:8083"
  #    restart: unless-stopped
  #    deploy:
  #      resources:
  #        limits:
  #          memory: 700m
  #    labels:
  #      logging: "promtail"

  auth-service:
    image: tienviet/gamelist-auth-service
    container_name: auth-service
    build:
      context: ./auth-service-go
      dockerfile: Dockerfile
    environment:
      - PORT=8082
    ports:
      - "8082:8082"
      - "6567:6567"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  user-service:
    image: tienviet/gamelist-user-service
    container_name: user-service
    build:
      context: ./user-service-dotnet
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_SECRETS_ID=bd82e8a2-e889-4963-87e9-6740a1609d78
    ports:
      - "8080:8080"
      - "6568:6568"
    volumes:
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"