version: "3.8"
name: 'spring-boot-microservices-gamelist'
services:
  gamelist-dev-db:
    image: postgres:16-alpine
    container_name: gamelist-dev-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5332:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  config-server:
    image: tienviet/gamelist-config-server
    container_name: config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      #      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/game
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8888:8888"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  gamelist-mongo-db:
    image: mongo:latest
    container_name: gamelist-mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=gamelist
    expose:
      - "27017"
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 500m
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s