// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: src/main/proto/common/common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common {

  /// <summary>Holder for reflection information generated from src/main/proto/common/common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for src/main/proto/common/common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJzcmMvbWFpbi9wcm90by9jb21tb24vY29tbW9uLnByb3RvEgZjb21tb24q",
            "RwoGVGlja2VyEgsKB1VOS05PV04QABIJCgVBUFBMRRABEgoKBkdPT0dMRRAC",
            "EgoKBkFNQVpPThADEg0KCU1JQ1JPU09GVBAEQjMKE2NvbS5nYW1lbGlzdC5j",
            "b21tb25QAVoaZ2l0aHViLmNvbS9nYW1lbGlzdC9jb21tb25iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Common.Ticker), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Ticker {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("APPLE")] Apple = 1,
    [pbr::OriginalName("GOOGLE")] Google = 2,
    [pbr::OriginalName("AMAZON")] Amazon = 3,
    [pbr::OriginalName("MICROSOFT")] Microsoft = 4,
  }

  #endregion

}

#endregion Designer generated code
