spring:
  application:
    name: scraper-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost}:8888

secrets:
  igdbClientKey: keyHere
  twitchLoginClientId: keyHere
  twitchLoginClientSecret: keyHere
  grant_type: client_credentials