apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: gamelist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      schedulerName: default-scheduler
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: {}
      terminationGracePeriodSeconds: 30
      containers:
        - name: api-gateway
          image: tienviet/gamelist-api-gateway:latest
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8989
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: GAME_SERVICE_URL
              value: "http://${GAME_SERVICE_SERVICE_HOST}:80"
            - name: AUTH_SERVICE_URL
              value: "http://${AUTH_SERVICE_SERVICE_HOST}:80"
            - name: SOCIAL_SERVICE_URL
              value: "http://${SOCIAL_SERVICE_SERVICE_HOST}:80"
            - name: USER_SERVICE_URL
              value: "http://${USER_SERVICE_SERVICE_HOST}:80"
            - name: MANAGEMENT_TRACING_ENABLED
              value: "true"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://${TEMPO_SERVICE_HOST}:${TEMPO_PORT}"
            - name: CONFIG_SERVER_URL
              value: "http://${CONFIG_SERVER_SERVICE_HOST}:80"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-key
          resources: {}
          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "1000m"