apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: gamelist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      restartPolicy: Always
      containers:
        - name: api-gateway
          image: tienviet/gamelist-api-gateway:latest
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8989
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: GAME_SERVICE_URL
              value: "http://${GAME_SERVICE_SERVICE_HOST}:${GAME_SERVICE_PORT}"
            - name: AUTH_SERVICE_URL
              value: "http://${AUTH_SERVICE_SERVICE_HOST}:${AUTH_SERVICE_PORT}"
            - name: SOCIAL_SERVICE_URL
              value: "http://${SOCIAL_SERVICE_SERVICE_HOST}:${SOCIAL_SERVICE_PORT}"
            - name: USER_SERVICE_URL
              value: "http://${USER_SERVICE_SERVICE_HOST}:${USER_SERVICE_PORT}"
            - name: MANAGEMENT_TRACING_ENABLED
              value: "true"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://${TEMPO_SERVICE_HOST}:${TEMPO_PORT}"
            - name: CONFIG_SERVER_URL
              value: "http://${CONFIG_SERVER_SERVICE_HOST}:${CONFIG_SERVER_SERVICE_PORT}"