apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: gamelist
spec:
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8989
  type: LoadBalancer