apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
  namespace: gamelist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      restartPolicy: Always
      containers:
        - name: game-service
          image: tienviet/gamelist-game-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
            - name: SWAGGER_API_GATEWAY_URL
              value: "http://${API_GATEWAY_SERVICE_HOST}:${API_GATEWAY_SERVICE_PORT}/game-service"
            - name: MANAGEMENT_TRACING_ENABLED
              value: "true"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://${TEMPO_SERVICE_HOST}:${TEMPO_PORT}"
            - name: CONFIG_SERVER_URL
              value: "http://${CONFIG_SERVER_SERVICE_HOST}:${CONFIG_SERVER_SERVICE_PORT}"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"