apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: gamelist
spec:
  selector:
    app: game-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8083
    name: http
  - protocol: TCP
    port: 6565
    targetPort: 6565
    name: grpc
  type: ClusterIP