   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: user-service
     namespace: gamelist
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: user-service
     strategy:
       rollingUpdate:
         maxSurge: 25%
         maxUnavailable: 25%
       type: RollingUpdate
     template:
       metadata:
         labels:
           app: user-service
       spec:
         schedulerName: default-scheduler
         restartPolicy: Always
         dnsPolicy: ClusterFirst
         securityContext: {}
         terminationGracePeriodSeconds: 30
         containers:
         - name: user-service
           image: tienviet/gamelist-user-service:latest
           imagePullPolicy: Always
           ports:
           - containerPort: 8080
           env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: USER_SECRETS_ID
              value: "bd82e8a2-e889-4963-87e9-6740a1609d78"
           resources: {}
          #  resources:
          #    requests:
          #      memory: "512Mi"
          #      cpu: "500m"
          #    limits:
          #      memory: "1Gi"
          #      cpu: "1000m"