apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: gamelist
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 6568
    targetPort: 6568
    name: grpc
  type: ClusterIP