@user_service_dotnet_HostAddress = http://localhost:5248

GET {{user_service_dotnet_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{user_service_dotnet_HostAddress}}/users/
Accept: application/json

###
GET {{user_service_dotnet_HostAddress}}/api/v1/user/userinfo
Accept: application/json
userId: 666a602d5d13cfef6ed583ac

###
GET {{user_service_dotnet_HostAddress}}/api/v1/user/userinfo
Accept: application/json
userId: 666a602d5d13cfef6ed583a