apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: gamelist
spec:
  selector:
    app: config-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  type: LoadBalancer