name: Game Service

on:
  push:
    paths:
      - game-service/**
    branches:
      - main
  pull_request:
    paths:
      - game-service/**
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/gamelist-game-service
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Java
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Step 3: Build the parent module
      - name: Build parent module
        run: ./mvnw clean install -f pom.xml

      # Step 4: Build the proto module
      - name: Build proto module
        run: ./mvnw clean install -f ./proto/pom.xml

      # Step 5: Build the game-service module
      - name: Build game-service module
        run: ./mvnw -ntp verify -f ./game-service/pom.xml

      # Step 6: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 7: Build and Publish Docker Image
      - name: Build and Publish Docker Image
        working-directory: ./game-service
        run: |
          ./mvnw spring-boot:build-image -DskipTests
          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
          docker push $DOCKER_IMAGE_NAME