name: User Service Dotnet

on:
  push:
    paths:
      - user-service-dotnet/**
    branches:
      - main
  pull_request:
    paths:
      - user-service-dotnet/**
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./user-service-dotnet
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/gamelist-user-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build with .NET
        run: dotnet build --configuration Release

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./user-service-dotnet
          file: ./user-service-dotnet/Dockerfile
          load: true
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gamelist-user-service
          build-args: |
            VAR_MONGO_DB=${{ secrets.VAR_MONGO_DB }}